name: CI to Docker Hub
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/github-action-data:${{ steps.vars.outputs.sha_short }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/github-action-data

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


      - name: Trigger train
        run: |
          curl -H "Authorization: token ${{ secrets.WF_TOKEN }}" \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          "https://api.github.com/repos/Zephons/github-action-train/dispatches" \
          -d '{"event_type": "new_dataset_${{ steps.vars.outputs.sha_short }}", "client_payload": {"dataset_commit_id": "${{ steps.vars.outputs.sha_short }}"}}'
